name: Quarto Publish  # Defining the name.

on:
  workflow_dispatch: # Allows for manual triggering of action without a new push being made. 
  workflow_call:
      secrets:
        token:
          required: true

jobs: # List of jobs
  build-deploy:
    runs-on: ubuntu-latest
    permissions: # Gives set of permissions to the action.
      contents: write
      pages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 
        with:
          token: ${{ secrets.token }}
          fetch-depth: 0 

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2 # standard quarto setup action

      - name: Install R Packages
        run: |
          Rscript -e 'install.packages(c(
            "dplyr", 
            "tidyr", 
            "stringr", 
            "DT", 
            "ggplot2", 
            "RColorBrewer"
          ), repos = "https://cloud.r-project.org")'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2 # Standard quarto publish action.
        with:
          target: gh-pages # sets the target branch.
          path: Quarto